
    create table Canchas (
        id integer generated by default as identity (start with 1),
        estaIluminada boolean not null,
        nombre varchar(255),
        color_codigo integer,
        primary key (id)
    )

    create table Colores (
        codigo integer generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (codigo)
    )

    create table ConstructoresPaletas (
        id integer generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (id)
    )

    create table Jugadores (
        id integer generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        nacimiento varbinary(255),
        nombre varchar(255),
        paleta_id integer,
        primary key (id)
    )

    create table Paletas (
        id integer generated by default as identity (start with 1),
        grosor integer not null,
        nombre varchar(255),
        color_codigo integer,
        constructor_id integer,
        primary key (id)
    )

    create table Participaciones (
        Partidos_id integer not null,
        jugadores_id integer not null
    )

    create table Partidos (
        id integer generated by default as identity (start with 1),
        fin_partido varbinary(255),
        inicio_partido varbinary(255),
        cancha_id integer,
        colorCancha_codigo integer,
        jugadorResponsable_id integer,
        primary key (id)
    )

    alter table Canchas 
        add constraint FK_g1bnp1vg9ta6vabbc7tp4pg3f 
        foreign key (color_codigo) 
        references Colores

    alter table Jugadores 
        add constraint FK_tq6vi8p9jpwmvb7hcdu435jp6 
        foreign key (paleta_id) 
        references Paletas

    alter table Paletas 
        add constraint FK_f5sdeegs37dwg4kfqxranyor6 
        foreign key (color_codigo) 
        references Colores

    alter table Paletas 
        add constraint FK_m1bcua5wq4p2qmm3nfqfjpqs9 
        foreign key (constructor_id) 
        references ConstructoresPaletas

    alter table Participaciones 
        add constraint FK_21ad08h3cou2luqlyyopmfimm 
        foreign key (jugadores_id) 
        references Jugadores

    alter table Participaciones 
        add constraint FK_pktldbwhjvdkx7fvf4io8lerx 
        foreign key (Partidos_id) 
        references Partidos

    alter table Partidos 
        add constraint FK_euaoyb7bsul9ym4v8u23cix4f 
        foreign key (cancha_id) 
        references Canchas

    alter table Partidos 
        add constraint FK_n3mis0mj5npu5uq1snupfavlw 
        foreign key (colorCancha_codigo) 
        references Colores

    alter table Partidos 
        add constraint FK_e8wnjrms435433s8qg4v7o9me 
        foreign key (jugadorResponsable_id) 
        references Jugadores
